from PIL import Image
import numpy as np
import cv2

def mitsua_credit(image: Image.Image) -> Image.Image:
    image = np.array(image)
    image = cv2.putText(image, "Generated by Mitsua Likes", (5, image.shape[0]-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 3, cv2.LINE_AA)
    image = cv2.putText(image, "Generated by Mitsua Likes", (5, image.shape[0]-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
    image = Image.fromarray(image)
    return image